# .github/workflows/ci.yml

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # 每天 02:00 UTC，按需改

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (no real network)
        run: |
          mkdir -p reports
          pytest -m "not network and not integration" -q

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/
          if-no-files-found: warn

  network:
    # 只在定时任务或手动触发时跑真外网
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (real network/integration)
        run: |
          mkdir -p reports
          pytest -m "network or integration" -q

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-network
          path: reports/
          if-no-files-found: warn
